### ISSUE TITLE
go error in the robot reporter

### ISSUE THREAD

**Issue by TeemuMoi** [joonvena/Robot-Reporter#1]
![Screenshot 2021-06-16 at 14 34 33](https://user-images.githubusercontent.com/85665979/122218156-d05c1f00-ceb6-11eb-8997-46f9f7f69fc8.png)

I get this kind of error while running the action. Do you know what it could be?

the actual action step is following:
  - name: Robot Reporter          
    uses: joonvena/robotframework-reporter-action@v0.1          
    env:            
         GH_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}            
         REPO_OWNER: ${{ env.REPOSITORY_OWNER  }}            
         COMMIT_SHA: ${{ github.sha }}            
         REPOSITORY: ${{ env.REPOSITORY_NAME }}            
         REPORT_PATH: ${{ github.workspace }}/reports

**Comment by joonvena** [comment]
This should be now fixed. Can you test and verify.

**Comment by TeemuMoi** [comment]
seems like working now. Thanks for the help
