### ISSUE TITLE
Add an option to flip Failed and Passed Tests lists

### ISSUE THREAD

**Issue by delca85** [joonvena/Robot-Reporter#14]
Hi!
In my company, we are using your [robotframework-reporter-action ](https://github.com/joonvena/robotframework-reporter-action).
We'd like to see the list of **Failed Tests** before the list of **Passed Tests**. I'm aware we could set `show_passed_tests` to `false` to hide completely the list of green tests, but we would like to keep it.

Would you see any value in me opening a PR here and in [robotframework-reporter-action ](https://github.com/joonvena/robotframework-reporter-action) to support this?

Thank you!

**Comment by joonvena** [comment]
Hi @delca85 you are more than welcomed to add this feature 👍 .

**Comment by delca85** [comment]
Hi @joonvena ! It took a bit, but I raised a PR to address this need :)

**Comment by joonvena** [comment]
This is now merged and available in version v2.5
